### ISSUE TITLE
Presentation should respect schema groups and fieldsets

### ISSUE THREAD

**Issue by liamb13** [sanity-io/visual-editing#1644]
**Describe the bug**

When clicking an Overlay, Presentations correctly navigates to the right Document. But it doesn't seem to understand 'groups'.

The correct field won't be highlighted until changing the active group to the right one.

**To Reproduce**

Set up a document schema with groups and use presentations to navigate between the two fields:
```
export default defineType({
  name: 'page',
  type: 'document',
  title: 'Page',
  groups: [
    {
      name: 'details',
      title: 'Details',
      default: true,
    },
    {
      name: 'content',
      title: 'Content',
    },
  ],
  fields: [
    defineField({
      group: 'details',
      name: 'title',
      title: 'Title (will navigate correctly)',
      type: 'string',
    }),
    defineField({
      group: 'content',
      name: 'subtitle',
      title: 'Subtitle (will not navigate correctly)',
      type: 'string',
    }),
  ]
})
```

**Expected behavior**

Presentations should be able to set the right active group.

**Comment by HumidBrains** [comment]
Some additional context: 

1. Since visual editing only opens the group that is set to the default, you can never have anything else than “All fields” set as the default group or you won’t be able to open any field of your choice.

2. If you have selected any other group just by browsing your content and then go back to clicking an overlay to open another field, that won’t work, nothing will happen, making it feel like the UI has hung, hence giving the impression there is a bug.

**Comment by rdunk** [comment]
This seems to be an upstream bug in the core. I've got a fix in the works, just needs some more testing, but hoping I can land it early next week.

**Comment by rdunk** [comment]
The fix has been merged into core so should make its way into the next studio release: https://github.com/sanity-io/sanity/pull/7154

**Comment by liamb13** [comment]
> The fix has been merged into core so should make its way into the next studio release: [sanity-io/sanity#7154](https://github.com/sanity-io/sanity/pull/7154)

🙌🏻🙌🏻

Thanks @rdunk
